### ISSUE TITLE
data availability from paper

### ISSUE THREAD

**Issue by sorjuela** [MairFlo/Targeted_transcriptomics#1]
Hi @MairFlo , 
Was wondering if you could walk me trough which data here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE135325 corresponds to the 3 donors in the paper (figure 3A). I would like to download the cellranger outputs (*.tsv.gz files) from each donor.

Thank you,
Stephany

**Comment by MairFlo** [comment]
Hi @sorjuela , 

sure thing: on https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE135325 you can download all the pre-processed raw data via the "GSE135325_RAW.tar". If you unpack this file you will get all the data used in the paper as "*.gz" files, which you need to unpack further. For figure 3, the two files "GSM4005486_Combined_PBMC_AbSeq_1_DBEC_MolsPerCell_with_SampleTag.csv" and "GSM4005487_Combined_PBMC_AbSeq_2_DBEC_MolsPerCell_with_SampleTag.csv" contain the molecule/cell table for RNA and protein, including the sample-tag information for the three donors (last column).

And just to clarify: the targeted transcriptomics data is not generated using cellranger, which is only applicable to 10x genomics data. Only the data shown in Suppl figure 2 is 10x data, and this one has been pre-processed using cellranger (those are all the "GSM4005490_10x_Donor3..." files)

Let me know if this clarified your question.
Best regards,
Florian

**Comment by sorjuela** [comment]
Great thanks! So here you already did demultiplexing, and the RNA and ADT values are raw counts right? no normalization yet.

Ah ok, sorry just saw your code, this data is basically your starting point for the analysis. 

Thank you!
Stephany
